# Global settings for the Vault deployment
global:
  enabled: true
  tlsDisable: false

# Configuration for the Vault Agent Injector
injector:
  enabled: true
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 250m

# Server configuration
server:
  enabled: true
  image:
    repository: "hashicorp/vault"
    tag: "1.17.2"
  resources:
    requests:
      memory: 256Mi
      cpu: 500m
    limits:
      memory: 8Gi
      cpu: 2000m
  dataStorage:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 10Gi
  extraEnvironmentVars:
    GOOGLE_PROJECT: "playground-s-11-8b0011ac"  # Replace with your GCP project ID
    GOOGLE_REGION: "us-central1"  # Replace with your GCP region
    VAULT_CACERT: /vault/tls/vault.ca
    VAULT_TLSCERT: /vault/tls/vault.crt
    VAULT_TLSKEY: /vault/tls/vault.key
  volumes:
    - name: tls
      secret:
        secretName: vault-tls
    
  volumeMounts:
    - name: tls
      mountPath: /vault/tls
      readOnly: true
   
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        disable_mlock = true
        listener "tcp" {
          tls_disable = false
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/tls/vault.crt"
          tls_key_file = "/vault/tls/vault.key"
          tls_client_ca_file = "/vault/tls/vault.ca"
          tls_min_version = "tls12"
        }
        
        storage "raft" {
          path = "/vault/data"
        
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/vault/tls/vault.ca"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file = "/vault/tls/vault.ca"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_ca_cert_file = "/vault/tls/vault.ca"
          }
        }
        
        seal "gcpckms" {
          project     = "playground-s-11-8b0011ac"
          region      = "us-central1"
          key_ring    = "vault-key-ring"
          crypto_key  = "vault-key"
        }
        
        service_registration "kubernetes" {}

# UI configuration
ui:
  enabled: true
  externalPort: 8200
